# This is script for https://cloud.google.com/cloud-build/
steps:
# Install
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']
# Build
- name: 'gcr.io/cloud-builders/yarn'
  args: ['run', 'build']
# Deploy
- name: gcr.io/cloud-builders/gsutil
  args: ["-m", "rsync", "-d", "-r", "build", "gs://scmp-client"]